### ISSUE TITLE
Pip install failed

### ISSUE THREAD

**Issue by ZarulHanifah** [nickp60/EzClermont#4]
Hello Nick,

I tried installing EzClermont, following step by step. It was going well...

```
conda create -n ezclermont biopython
conda activate ezclermont
```

* I think it should be `conda create -n ezclermont biopython`, not `conda create -n ez biopython`

... until it failed at the pip install stage

```
(ezclermont) ahbui@TUF[~] pip install ezclermont
Collecting ezclermont
  Downloading ezclermont-0.6.2.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ahbui/Zarul/Software/anaconda3/envs/ezclermont/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0qpruu7b/ezclermont_ca821db144f847fc8d845181fc60f073/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0qpruu7b/ezclermont_ca821db144f847fc8d845181fc60f073/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q6cvphlz
         cwd: /tmp/pip-install-0qpruu7b/ezclermont_ca821db144f847fc8d845181fc60f073/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0qpruu7b/ezclermont_ca821db144f847fc8d845181fc60f073/setup.py", line 38, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-0qpruu7b/ezclermont_ca821db144f847fc8d845181fc60f073/setup.py", line 38, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Can you try and see what happened please?

Thank you.

**Comment by nickp60** [comment]
Hi  @ZarulHanifah thanks for reporting this!  I was able to reproduce the issue. Those instructions I think are a bit date, from before ezclermont was on conda. I'll push a fix for the `ParsedRequirement` thing in the meantime though, its similar to [this issue](https://stackoverflow.com/questions/62114945/attributeerror-parsedrequirement-object-has-no-attribute-req).  For now, try running `conda install ezclermont`

**Comment by nickp60** [comment]
This should be resolved now, let me know if you have any further issues!
